deployment:
  version: IMAGE_VERSION
  imageURL: 180935779261.dkr.ecr.us-east-1.amazonaws.com/expense/frontend
hpa:
  utilisation: 5
tgb:
  arn: arn:aws:elasticloadbalancing:us-east-1:180935779261:targetgroup/expense-dev/fe65a7e04a456838

  # always change the arm on new creation of expense terget group arn --> arn:aws:elasticloadbalancing:us-east-1:180935779261:targetgroup/expense-dev/1c4af27a5ed48bf4

  #arn:aws:elasticloadbalancing:us-east-1:180935779261:targetgroup/expense-dev/fe65a7e04a456838